---
driver_plugin: digitalocean
driver_config:
  digitalocean_client_id: <%= ENV['DO_CLIENT_ID'] %>
  digitalocean_api_key: <%= ENV['DO_API_KEY'] %>
  flavor_id: 63
  ssh_key_ids: <%= ENV['DO_SSH_KEY_IDS'] %>
  require_chef_omnibus: latest

platforms:
- name: ubuntu-12.10
  driver_config:
    image_id: 25489
  run_list:
  - recipe[apt]

- name: debian-6.0.7
  driver_config:
    image_id: 12573
  run_list:
  - recipe[apt]

suites:
- name: default
  run_list:
  - recipe[minecraft]
  - recipe[minitest-handler]
  attributes:
