default['minecraft']['user']                = 'minecraft'
default['minecraft']['install_dir']         = '/srv/minecraft'

default['minecraft']['banned-ips']          = []
default['minecraft']['banned-players']      = []
default['minecraft']['white-list-users']    = []
default['minecraft']['ops']                 = []

default['minecraft']['allow-nether']        = true
default['minecraft']['level-name']          = 'world'
default['minecraft']['enable-query']        = false
default['minecraft']['allow-flight']        = false
default['minecraft']['server-port']         = 25565
default['minecraft']['level-type']          = 'DEFAULT'
default['minecraft']['enable_rcon']         = false
default['minecraft']['level-seed']          = ''
default['minecraft']['server-ip']           = ''
default['minecraft']['max-build-height']    = 256
default['minecraft']['spawn-npcs']          = true
default['minecraft']['white-list']          = false
default['minecraft']['spawn-animals']       = true
default['minecraft']['online-mode']         = true
default['minecraft']['pvp']                 = true
default['minecraft']['difficulty']          = 1
default['minecraft']['gamemode']            = 0
default['minecraft']['max-players']         = 20
default['minecraft']['spawn-monsters']      = true
default['minecraft']['generate-structures'] = true
default['minecraft']['view-distance']       = 10
default['minecraft']['motd']                = 'A Minecraft Server'
